all:
  host: "0.0.0.0"
  port: 3300
  jwt:
    expiresIn: 604800
    
dev:
  debug: false
  web: 
    # mode: "native"
    mode: "optimized"
  clock:
    tick_rate: 50
  secret: "Zn36aEDySypAqPLfp4QXVHGfC_PMXbVKkZ1P_2xjfrJRUtLavr"
  admin:
    email: "elyon@younity-mc.fr"
    password: "admin" 

prod:
  debug: false
  web: 
    mode: "optimized"
  clock:
    tick_rate: 50
  secret: "aDhX0RjDo-9oqXcvvOr_l1fKawZN2NPYTzA0BNXcS1HXVTSqK6"
  admin:
    email: "elyon@younity-mc.fr"
    password: "CoDM5mOly8vLhdAyoj_r" 
